### ISSUE TITLE
anyway to add layers?

### ISSUE THREAD

**Issue by ohaddahan** [storyscript/tracing-wasm#30]
Couldn't find how to add a layer like I do with regular tracing crate.

**Comment by WorldSEnder** [comment]
This crate has not received attention from its maintainer for some while (which is their fair right). I wanted the same functionality a while ago, since layers are more composable, I rolled my own [`tracing-web`](https://crates.io/crates/tracing-web) crate to implement this. I'm open for feedback and would merge it back here in case this crate receives attention again in the future.

**Comment by ohaddahan** [comment]
> tracing-web

I ended up doing this https://github.com/block-mesh/block-mesh-monorepo/blob/master/libs/logger-leptos/src/leptos_tracing.rs .
I think I copied over some other crate that implemented layers and edit it to my specific needs.
